### ISSUE TITLE
Remove yarn.lock

### ISSUE THREAD

**Issue by msansoni** [race-hub/f1-game-udp-parser#5]
@jonybur now we are using TS and you've updated package.json and we have a package-lock.json, we should remove yarn.lock. Any objections?

**Comment by jonybur** [comment]
No objections over here 👍

**Comment by jonybur** [comment]
Hey @msansoni . It's been a pretty hectic week for me, I can only imagine what it was like in Australia. Whenever you want to keep moving forward with the race-hub projects just let me know so that we can perhaps discuss visualisation or set up the next steps to follow. Thank you

**Comment by msansoni** [comment]
Sounds good @jonybur, yes very hectic, but if they move shutdown earlier, should give a great oppertunity to develop this!
The main thing at the moment is creating a TypeScript time series like [pondjs](http://software.es.net/pond/#/), which can store the data packets in real time, and perform rapid data extraction for visualisation, both for windows of data between two timestamps, and at the cursor in the data, for legends and gauge style displays.
I've had a few attempts at creating this library in previous iterations of this project, in all cases i've had to resort to batching the timeseries into groups of timestamps (10s intervals or so) in order to limit the max size of each array, perform push/findIndex calls on them etc. however I'm sure you'll have some ideas as well for a better implementation.
we could even use pondjs, i'd just like to stress test it beforehand, or use something more bespoke, because we are fortunate in our case that although there are a large number of 'channels' of data, they are all coming in packets with the same timestamp, so we can keep a common timestamp column for multiple columnar values.

**Comment by jonybur** [comment]
@msansoni We should consider data storage depending on the type and the amount of data that we want to present the user (including charts, gauges). So, how are we going to present the information to the user? Perhaps it would be best to create a quick visual mockup for use cases in order to understand what we want to achieve first. This will give us some insight into the type of data that we want to store, and where (DB or RAM).
For my previous project timeseries I used a simple matrix, where matrix[ms] stores the information of the race for that moment in time.
So for example:
array = [[ { m_speed: 0, (...) } ]]
Where array[ms][car_index][m_speed] returns the speed of that car in that specific moment
