### ISSUE TITLE
Unable to restart parser after stopping

### ISSUE THREAD

**Issue by msansoni** [race-hub/f1-game-udp-parser#6]
We check whether the socket has been defined in the start function: https://github.com/race-hub/f1-game-udp-parser/blob/75b5d64cfc7f2ea7ffe59d9b812f5941dd2026fc/lib/index.ts#L32

However when we stop the parser we set it to undefined:
https://github.com/race-hub/f1-game-udp-parser/blob/75b5d64cfc7f2ea7ffe59d9b812f5941dd2026fc/lib/index.ts#L57

This means if a user is to stop (pause) the parser, we would need to re-initialise the parser to restart it. Perhaps we should re-initialise the socket `dgram.createSocket('udp4')` when we close the socket?

**Comment by msansoni** [comment]
@jonybur just issuing it rather than changing myself, as I see this logic carried over from previous iterations, I wondered if there was a specific reason why it was here, or whether we can just change it?

**Comment by jonybur** [comment]
@msansoni Yes, you're correct, this has been carried over since the first iteration of the codebase. The parser wasn't meant to be restarted once it was stopped. I am adding the feature [in this PR](https://github.com/race-hub/f1-game-udp-parser/pull/7); I am adding tests to cover the restarting of the socket

**Comment by msansoni** [comment]
Closed by #7
